# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Torresmo < Formula
  desc "Experimental torrent client and server"
  homepage "https://github.com/mvrilo/torresmo/"
  version "0.1.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_darwin_amd64.tar.gz"
      sha256 "b9c7a14e02eac3a713217928c920da9d310575e96f7eb0709ad82c8e49fc9a08"
    end
    if Hardware::CPU.arm?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_darwin_arm64.tar.gz"
      sha256 "791fa1b0aac4d7a8db1903ada3acbba637a7bcb51a403682db3ae6542fdd59de"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_linux_amd64.tar.gz"
      sha256 "f5e20578fb731e0eaf08c226e0dc3148f9c9e04532faa99083adf29b000f6fdf"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_linux_arm64.tar.gz"
      sha256 "ebe4bed4ac37b42a655085b8c157fa878c71d0aa2aacea1fb5b3a65f82d362ab"
    end
  end

  def install
    bin.install "torresmo"
  end

  test do
    system "#{bin}/torresmo -v"
  end
end
