# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Torresmo < Formula
  desc "Experimental Torrent client and server"
  homepage "https://github.com/mvrilo/torresmo/"
  version "0.1.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_darwin_amd64.tar.gz"
      sha256 "ececad823b91241eacc4bd62378c66088a5c833aaf15ab09767ef1acd3e739d1"
    end
    if Hardware::CPU.arm?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_darwin_arm64.tar.gz"
      sha256 "3843f22f07eace770bf85e5c0bba18bdd596ee66f56704f9f5bca6bc75ae1a9d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_linux_amd64.tar.gz"
      sha256 "3421070dd07e492a3b84f7f48e96900557b3bc8aebb1f9a5223344d05325d5a9"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_linux_arm64.tar.gz"
      sha256 "70c0fb6ae9ca54ea8604bae3213581dda2fcb74014d6e4d101790c249e3f7586"
    end
  end

  def install
    bin.install "torresmo"
  end
end
