# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Torresmo < Formula
  desc "Experimental Torrent client and server"
  homepage "https://github.com/mvrilo/torresmo/"
  version "0.1.1"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_darwin_amd64.tar.gz"
      sha256 "5957354f0dc189bf3610d4abf7c1d9e3319eee1f45af540be2931073a6cf024c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_darwin_arm64.tar.gz"
      sha256 "aabc337ac5983b3c922fd831fc2a221a3ad3b4b4d6e07a8c64bddcb107f9bbaf"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_linux_amd64.tar.gz"
      sha256 "5ff5d517fcccbc373f6b5baac88935305c22b71a72b44500fdaba6060197e4ed"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mvrilo/torresmo/releases/download/v0.1.1/torresmo_0.1.1_linux_arm64.tar.gz"
      sha256 "ee10679150b7a9c0f448d88a3e09251bbeeb0fa883f81243ff7dd49640863809"
    end
  end

  def install
    bin.install "torresmo"
  end
end
